[package]
name = "masters"
version = "0.1.0"
edition = "2024"

[dependencies]
dasp-rs = "0.1.0"
hound = "3.5.1"
indicatif = "0.17.11"
num-complex = "0.4.6"
rand = "0.9.0"
rustfft = "6.2.0"
thiserror = "2.0.12"
